theme: jekyll-theme-minimal

# Site Settings
locale                   : "en-US"
title                    : "Yanwen Xu / HomePage"
title_separator          : "-"
name                     : &name "Yanwen Xu"
description              : &description "personal description"
